[package]
name = "bevy_light_2d"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_winit",
    "bevy_sprite"
] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
