[package]
name = "bevy_light_2d"
version = "0.1.0"
edition = "2021"
categories = ["game-engines", "graphics", "rendering", "gamedev"]
description = "General purpose 2d lighting for the Bevy game engine."
authors = ["James Gayfer"]
repository = "https://github.com/jgayfer/bevy_light_2d"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_winit",
    "bevy_sprite",
    "x11"
] }

[lints.clippy]
type_complexity = "allow"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
